name: Build and upload docker image
on:
  pull_request:
    branches:
      - "master"
  push:
    branches:
      - '**'

      
jobs:
  build-upload:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3

      
      - name: Check if docker available or not
        run : which docker;echo ${GITHUB_BASE_REF}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

   
